module tb_ctrl;

    // Inputs applied to the control unit.
    reg [5:0] opcode;
    reg [5:0] funct;

    // Output control signals generated by the control unit.
    wire RegDst;
    wire Branch;
    wire MemRead;
    wire MemtoReg;
    wire [1:0] ALUOp;
    wire MemWrite;
    wire ALUSrc;
    wire RegWrite;
    wire Jump;
    wire JAL;
    wire JR;
    wire LUI;
    wire ZeroExt;

    // Instantiate the Unit Under Test (UUT).
    ctrl uut (
        .opcode(opcode),
        .funct(funct),
        .RegDst(RegDst),
        .Branch(Branch),
        .MemRead(MemRead),
        .MemtoReg(MemtoReg),
        .ALUOp(ALUOp),
        .MemWrite(MemWrite),
        .ALUSrc(ALUSrc),
        .RegWrite(RegWrite),
        .Jump(Jump),
        .JAL(JAL),
        .JR(JR),
        .LUI(LUI),
        .ZeroExt(ZeroExt)
    );

    // Counts the number of failed tests.
    integer errors = 0;

    // Task used to compare the actual outputs
    // against the expected outputs for each instruction.
    task check;
        input        exp_RegDst;
        input        exp_Branch;
        input        exp_MemRead;
        input        exp_MemtoReg;
        input [1:0]  exp_ALUOp;
        input        exp_MemWrite;
        input        exp_ALUSrc;
        input        exp_RegWrite;
        input        exp_Jump;
        input        exp_JAL;
        input        exp_JR;
        input        exp_LUI;
        input        exp_ZeroExt;
        input [127:0] instr_name;
        begin

            // Verify whether all generated control signals
            // match the expected values.
            if (RegDst   !== exp_RegDst   ||
                Branch   !== exp_Branch   ||
                MemRead  !== exp_MemRead  ||
                MemtoReg !== exp_MemtoReg ||
                ALUOp    !== exp_ALUOp    ||
                MemWrite !== exp_MemWrite ||
                ALUSrc   !== exp_ALUSrc   ||
                RegWrite !== exp_RegWrite ||
                Jump     !== exp_Jump     ||
                JAL      !== exp_JAL      ||
                JR       !== exp_JR       ||
                LUI      !== exp_LUI      ||
                ZeroExt  !== exp_ZeroExt) begin

                // Report test failure.
                $display("FAIL [%s]", instr_name);

                // Display actual values.
                $display("got      RegDst=%b Branch=%b MemRead=%b MemtoReg=%b ALUOp=%b MemWrite=%b ALUSrc=%b RegWrite=%b Jump=%b JAL=%b JR=%b LUI=%b ZeroExt=%b",
                          RegDst, Branch, MemRead, MemtoReg, ALUOp, MemWrite, ALUSrc, RegWrite, Jump, JAL, JR, LUI, ZeroExt);
                
                // Display expected values.                
                $display("expected RegDst=%b Branch=%b MemRead=%b MemtoReg=%b ALUOp=%b MemWrite=%b ALUSrc=%b RegWrite=%b Jump=%b JAL=%b JR=%b LUI=%b ZeroExt=%b",
                          exp_RegDst, exp_Branch, exp_MemRead, exp_MemtoReg, exp_ALUOp, exp_MemWrite, exp_ALUSrc, exp_RegWrite, exp_Jump, exp_JAL, exp_JR, exp_LUI, exp_ZeroExt);

                errors = errors + 1;
            end
            else begin
                // Report successful test.
                $display("PASS [%s]", instr_name);
            end
        end
    endtask

    initial begin

        // Generate waveform file for GTKWave.
        $dumpfile("sim/tb_ctrl.vcd");
        $dumpvars(0, tb_ctrl);


        //------------------------------------------------------------------
        // R-type instruction test
        //------------------------------------------------------------------
        opcode = 6'b000000; funct = 6'b100000; #10;
        check(1, 0, 0, 0, 2'b10, 0, 0, 1, 0, 0, 0, 0, 0, "R-type");

        //------------------------------------------------------------------
        // jr instruction test
        //------------------------------------------------------------------
        opcode = 6'b000000; funct = 6'b001000; #10;
        check(0, 0, 0, 0, 2'b00, 0, 0, 0, 0, 0, 1, 0, 0, "jr");

        //------------------------------------------------------------------
        // lw instruction test
        //------------------------------------------------------------------
        opcode = 6'b100011; funct = 6'b000000; #10;
        check(0, 0, 1, 1, 2'b00, 0, 1, 1, 0, 0, 0, 0, 0, "lw");

        //------------------------------------------------------------------
        // sw instruction test
        //------------------------------------------------------------------
        opcode = 6'b101011; funct = 6'b000000; #10;
        check(0, 0, 0, 0, 2'b00, 1, 1, 0, 0, 0, 0, 0, 0, "sw");

        //------------------------------------------------------------------
        // beq instruction test
        //------------------------------------------------------------------
        opcode = 6'b000100; funct = 6'b000000; #10;
        check(0, 1, 0, 0, 2'b01, 0, 0, 0, 0, 0, 0, 0, 0, "beq");

        //------------------------------------------------------------------
        // bne instruction test
        //------------------------------------------------------------------
        opcode = 6'b000101; funct = 6'b000000; #10;
        check(0, 1, 0, 0, 2'b01, 0, 0, 0, 0, 0, 0, 0, 0, "bne");

        //------------------------------------------------------------------
        // addi instruction test
        //------------------------------------------------------------------
        opcode = 6'b001000; funct = 6'b000000; #10;
        check(0, 0, 0, 0, 2'b11, 0, 1, 1, 0, 0, 0, 0, 0, "addi");

        //------------------------------------------------------------------
        // andi instruction test
        //------------------------------------------------------------------
        opcode = 6'b001100; funct = 6'b000000; #10;
        check(0, 0, 0, 0, 2'b11, 0, 1, 1, 0, 0, 0, 0, 1, "andi");

        //------------------------------------------------------------------
        // ori instruction test
        //------------------------------------------------------------------
        opcode = 6'b001101; funct = 6'b000000; #10;
        check(0, 0, 0, 0, 2'b11, 0, 1, 1, 0, 0, 0, 0, 1, "ori");

        //------------------------------------------------------------------
        // xori instruction test
        //------------------------------------------------------------------
        opcode = 6'b001110; funct = 6'b000000; #10;
        check(0, 0, 0, 0, 2'b11, 0, 1, 1, 0, 0, 0, 0, 1, "xori");

        //------------------------------------------------------------------
        // slti instruction test
        //------------------------------------------------------------------
        opcode = 6'b001010; funct = 6'b000000; #10;
        check(0, 0, 0, 0, 2'b11, 0, 1, 1, 0, 0, 0, 0, 0, "slti");

        //------------------------------------------------------------------
        // sltiu instruction test
        //------------------------------------------------------------------
        opcode = 6'b001011; funct = 6'b000000; #10;
        check(0, 0, 0, 0, 2'b11, 0, 1, 1, 0, 0, 0, 0, 0, "sltiu");

        //------------------------------------------------------------------
        // lui instruction test
        //------------------------------------------------------------------
        opcode = 6'b001111; funct = 6'b000000; #10;
        check(0, 0, 0, 0, 2'b00, 0, 1, 1, 0, 0, 0, 1, 0, "lui");

        //------------------------------------------------------------------
        // j instruction test
        //------------------------------------------------------------------
        opcode = 6'b000010; funct = 6'b000000; #10;
        check(0, 0, 0, 0, 2'b00, 0, 0, 0, 1, 0, 0, 0, 0, "j");

        //------------------------------------------------------------------
        // jal instruction test
        //------------------------------------------------------------------
        opcode = 6'b000011; funct = 6'b000000; #10;
        check(0, 0, 0, 0, 2'b00, 0, 0, 1, 1, 1, 0, 0, 0, "jal");

        //------------------------------------------------------------------
        // Invalid opcode test
        //------------------------------------------------------------------
        opcode = 6'b111111; funct = 6'b000000; #10;
        check(0, 0, 0, 0, 2'b00, 0, 0, 0, 0, 0, 0, 0, 0, "default");

        // Print final result.
        if (errors == 0)
            $display("ALL PASS - %0d tests", 16);
        else begin
            $display("FAILED - %0d error(s)", errors);
            $finish(1);
        end

        $finish;
    end

endmodule
