module tb_pc;

    // Clock signal.
    reg clk;

    // Reset signal.
    reg Reset;

    // Next value to be loaded into the Program Counter.
    reg [31:0] nextPC;

    // Current Program Counter value generated by the DUT.
    wire [31:0] currentPC;

    // Instantiate the Unit Under Test (UUT).
    pc uut (
        .clk(clk),
        .Reset(Reset),
        .nextPC(nextPC),
        .currentPC(currentPC)
    );

    // Counts the number of failed tests.
    integer errors = 0;

    // Generate a clock with a 10 ns period.
    // The clock toggles every 5 ns.
    always #5 clk = ~clk;


    // Compares the actual PC value against the expected value.
    task check;
        input [31:0] expected;
        input [31:0] actual;
        input [127:0] test_name;
        begin

            // Report a failure if the values do not match.
            if (actual !== expected) begin
                $display("FAIL [%s]: got %h, expected %h", test_name, actual, expected);
                errors = errors + 1;
            end
            
            // Report a successful test.
            else begin
                $display("PASS [%s]", test_name);
            end
        end
    endtask

    initial begin
        // Generate waveform file for GTKWave.
        $dumpfile("sim/tb_pc.vcd");
        $dumpvars(0, tb_pc);

        // Initialize test signals.
        clk =  1'b0;
        Reset = 1'b1;
        nextPC = 32'h00000000;

        //------------------------------------------------------------------
        // Reset test
        // The PC must immediately assume address 0.
        //------------------------------------------------------------------
        #1;
        check(32'h00000000, currentPC, "reset");

        // Release reset and start normal operation.
        Reset = 0;

        //------------------------------------------------------------------
        // Update PC to address 0x00000004
        //------------------------------------------------------------------
        nextPC = 32'h00000004;
        @(posedge clk);
        #1;
        check(32'h00000004, currentPC, "update to 4");


        //------------------------------------------------------------------
        // Update PC to address 0x00000008
        //------------------------------------------------------------------
        nextPC = 32'h00000008;
        @(posedge clk);
        #1;
        check(32'h00000008, currentPC, "update to 8");

        //------------------------------------------------------------------
        // Update PC to address 0x00000010
        //------------------------------------------------------------------
        nextPC = 32'h00000010;
        @(posedge clk);
        #1;
        check(32'h00000010, currentPC, "update to 16");

        //------------------------------------------------------------------
        // Update PC to address 0x00000020
        //------------------------------------------------------------------
        nextPC = 32'h00000020;
        @(posedge clk);
        #1;
        check(32'h00000020, currentPC, "update to 32");


        //------------------------------------------------------------------
        // Reset priority test
        // Reset must force the PC back to address 0 even after
        // several successful updates.
        //------------------------------------------------------------------
        Reset = 1;
        #1;
        check(32'h00000000, currentPC, "reset after updates");

        // Print the final test summary.
        if (errors == 0)
            $display("ALL PASS");
        else begin
            $display("FAILED - %0d error(s)", errors);
            $finish(1);
        end

        $finish;
    end

endmodule
